name: ipwhitelist
version: '${project.version}'
main: org.exp.ipwhitelist.Ipwhitelist
api-version: '1.20'
commands:
  register-admin:
    description: "Register admin for execute commands."
    usage: "/register-admin <username> <password> <adminNickname>"
  add-player:
    description: "Add Player to whitelist."
    usage: "/add-player <PlayerNickName>"
  remove-player:
    description: "Remove Player to whitelist."
    usage: "/remove-player <PlayerNickName>"
  whitelist-start:
    description: "Turn on/off plugin"
  wl-login:
    description: "Login for create session."
    usage: "/wl-login <username> <passwd>"
